### ISSUE TITLE
To-Do list Application in java

### ISSUE THREAD

**Issue by GILBERTKETER** [VineeTagarwaL-code/30-Java-Projects#3]

**Comment by VineeTagarwaL-code** [comment]
@GILBERTKETER add #3 in your PR to add your PR here

**Comment by GILBERTKETER** [comment]
Added sir

**Comment by GILBERTKETER** [comment]
> @GILBERTKETER add #3 in your PR to add your PR here

Yes sir, how about merging the PR sir?
I dont know

**Comment by VineeTagarwaL-code** [comment]
add #3 as comment in your pull request it will get joined here
